### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by lasermtv07** [Prabal1902/Movie-Ticketing-System--by-Prabal-#3]
if I choose that I have already registered on my PC like this:
```
Have you already registered?
type 1 for YES
type 0 for NO
To log into ADMIN please enter your ADMIN CODE


your answer---->1


~~~~~WELCOME BACK!~~~~~
```
i get this error:
```Traceback (most recent call last):
  File "P\path", line 213, in <module>
    register()
  File "P\path", line 179, in register
    with open("customer table.csv", mode="a", newline="") as f:
PermissionError: [Errno 13] Permission denied: 'customer table.csv'
```

**Comment by lasermtv07** [comment]
EDIT: does not happen when Excel IS closed
